# Generated by Django 5.0.7 on 2024-07-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight_class', models.CharField(max_length=100)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('knockout_wins', models.IntegerField()),
                ('submission_wins', models.IntegerField()),
                ('decision_wins', models.IntegerField()),
            ],
        ),
    ]
