# Generated by Django 5.0.7 on 2024-07-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='decision_wins',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='knockout_wins',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='submission_wins',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='weight_class',
        ),
        migrations.AddField(
            model_name='fighter',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='losses_by_decision',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='losses_by_knockout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='losses_by_submission',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='reach',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins_by_decision',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins_by_knockout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins_by_submission',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='losses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='wins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
