# Generated by Django 5.0.7 on 2024-07-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0002_remove_fighter_decision_wins_remove_fighter_draws_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='style',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
