# Generated by Django 5.0.7 on 2024-07-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0003_alter_fighter_name_alter_fighter_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='division',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='style',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
